### PR TITLE
Add browser sync command and link

### PR DESCRIPTION
**Pull request by amitaibu**
btw, I've noticed that even if I go to the `localhost:4000` - the page doesn't auto-reload. Am I'm missing something?

### CODE REVIEW

**Comment by yamadapc** [comment]
Thanks for the patch! For browser-sync to work you need to patch ‘DevelMain.hs‘.

Try ‘yesod-fast-devel init‘.

This is pretty flaky thoigh, needs some polish.

**Comment by amitaibu** [comment]
Thanks, I'll try.

> his is pretty flaky thoigh, needs some polish.

yeah, I'm still trying to figure out what's the best way 😄 

btw, would be great if you could enable the `issues` option in the repo.

**Comment by yamadapc** [comment]
I just did; spam me away with what's too bad. 😄

If you use Emacs, it has very good support for reloading develmain... Then the patched version of develmain with `browser-sync` gives you pretty instant, good to work with browser reload.

The issue with this atm is that:
- The interface is messed-up
- It won't restart the process if you change dependencies (which would be simple to add)
- It doesn't queue changes in any way, so if you go about changing lots of things it might not work properly

**Comment by amitaibu** [comment]
> I just did; spam me away with what's too bad. 😄

👍 

> If you use Emacs

I use Atom - but most docs seem to be only about Emacs. 

My goal is to find a good solution that we can document clearly in yesod-scaffold

**Comment by amitaibu** [comment]
`yesod-fast-devel init` works!

Maybe worth adding it and the fact the site is in `localhost:4000` to the README?

**Comment by yamadapc** [comment]
https://github.com/haskellbr/yesod-fast-devel/commit/63374a2c36c218b4ba17b591983e5b57f0dc94d4 ?

**Comment by amitaibu** [comment]
👍

**Pull request merged**
